# Generated by Django 2.2.16 on 2022-07-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
