# Generated by Django 2.2.16 on 2022-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220720_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.Title', verbose_name='отзыв'),
            preserve_default=False,
        ),
    ]
